exclude:
  - vendor
  - "*.Rmd"
baseurl: /env-info
gems: # https://pages.github.com/versions/
  - jekyll-sitemap
  - jekyll-mentions
#  - jemoji
#  - jekyll-last-modified-at
#  - jekyll-redirect-from
#  - jekyll-feed
#  - jekyll-gist
  
# Conversion
markdown:    kramdown
highlighter: pygments
kramdown:
  input: GFM
